classdef AnnualUniqueSeriesConsumptionValue < macrobond.JSONMapper
% AnnualUniqueSeriesConsumptionValue No description provided
% 
% AnnualUniqueSeriesConsumptionValue Properties:
%   value - Unique series consumed in the last 12 months - type: int32
%   lastUpdate - The last update timestamp for the usage statistics - type: datetime

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 3.0.0


    % Class properties
    properties
        % value - Unique series consumed in the last 12 months - type: int32
        value int32 { macrobond.JSONMapper.fieldName(value,"value")}
        % lastUpdate - The last update timestamp for the usage statistics - type: datetime
        lastUpdate datetime { macrobond.JSONMapper.stringDatetime(lastUpdate,'yyyy-MM-dd''T''HH:mm:ss.SSSZ', 'TimeZone', 'local'), macrobond.JSONMapper.fieldName(lastUpdate,"lastUpdate")}
    end

    % Class methods
    methods
        % Constructor
        function obj = AnnualUniqueSeriesConsumptionValue(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { macrobond.JSONMapper.ConstructorArgument } = []
                inputs.?macrobond.models.AnnualUniqueSeriesConsumptionValue
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

