classdef DateTypeDefinedEntityRequest < macrobond.JSONMapper
% DateTypeDefinedEntityRequest Request of an entity and an optional timestamp of last modification
% 
% DateTypeDefinedEntityRequest Properties:
%   name - The name of the entity - type: string
%   ifModifiedSince - If specified, the entity will only be returned if modified since the specified time. If not, the ErrorCode field of the response will be NotModified (304). - type: datetime
%   dateEndOfPeriod - If specified, dates will return as the last date in the period - type: logical

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % name - The name of the entity - type: string
        name string { macrobond.JSONMapper.fieldName(name,"name")}
        % ifModifiedSince - If specified, the entity will only be returned if modified since the specified time. If not, the ErrorCode field of the response will be NotModified (304). - type: datetime
        ifModifiedSince datetime { macrobond.JSONMapper.stringDatetime(ifModifiedSince,'yyyy-MM-dd''T''HH:mm:ss.SSSZ', 'TimeZone', 'local'), macrobond.JSONMapper.fieldName(ifModifiedSince,"ifModifiedSince")}
        % dateEndOfPeriod - If specified, dates will return as the last date in the period - type: logical
        dateEndOfPeriod logical { macrobond.JSONMapper.fieldName(dateEndOfPeriod,"dateEndOfPeriod")}
    end

    % Class methods
    methods
        % Constructor
        function obj = DateTypeDefinedEntityRequest(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { macrobond.JSONMapper.ConstructorArgument } = []
                inputs.?macrobond.models.DateTypeDefinedEntityRequest
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

