classdef ReleaseEventItem < macrobond.JSONMapper
% ReleaseEventItem No description provided
% 
% ReleaseEventItem Properties:
%   expectedReleaseTime - The time when Macrobond expects the next update. This takes known delays and other factors into account. - type: datetime
%   sourceReleaseTime - The time when the next update will be published according to the data source - type: datetime
%   referencePeriodDate - The reference period of the expected update - type: datetime
%   comment - type: string
%   kind - The kind of event this item represents  0 = Unknown (Unknown)  1 = Revised (Revised values)  2 = New (New values) - type: ReleaseEventItemKind

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % expectedReleaseTime - The time when Macrobond expects the next update. This takes known delays and other factors into account. - type: datetime
        expectedReleaseTime datetime { macrobond.JSONMapper.stringDatetime(expectedReleaseTime,'yyyy-MM-dd''T''HH:mm:ss.SSSZ', 'TimeZone', 'local'), macrobond.JSONMapper.fieldName(expectedReleaseTime,"expectedReleaseTime")}
        % sourceReleaseTime - The time when the next update will be published according to the data source - type: datetime
        sourceReleaseTime datetime { macrobond.JSONMapper.stringDatetime(sourceReleaseTime,'yyyy-MM-dd''T''HH:mm:ss.SSSZ', 'TimeZone', 'local'), macrobond.JSONMapper.fieldName(sourceReleaseTime,"sourceReleaseTime")}
        % referencePeriodDate - The reference period of the expected update - type: datetime
        referencePeriodDate datetime { macrobond.JSONMapper.stringDatetime(referencePeriodDate,'yyyy-MM-dd''T''HH:mm:ss.SSSZ', 'TimeZone', 'local'), macrobond.JSONMapper.fieldName(referencePeriodDate,"referencePeriodDate")}
        % comment - type: string
        comment string { macrobond.JSONMapper.fieldName(comment,"comment")}
        % kind - The kind of event this item represents  0 = Unknown (Unknown)  1 = Revised (Revised values)  2 = New (New values) - type: ReleaseEventItemKind
        kind  { macrobond.JSONMapper.fieldName(kind,"kind")}
    end

    % Class methods
    methods
        % Constructor
        function obj = ReleaseEventItem(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { macrobond.JSONMapper.ConstructorArgument } = []
                inputs.?macrobond.models.ReleaseEventItem
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

