classdef ReleaseEventItemKind < macrobond.JSONEnum
% ReleaseEventItemKind   0 = Unknown (Unknown)  1 = Revised (Revised values)  2 = New (New values)

    % This file is automatically generated using OpenAPI
    % Specification version: v1
    % MATLAB Generator for OpenAPI version: 1.0.0
    

    properties  (Constant)
        baseType = "int32"
    end

    enumeration 
        Unknown (int32(0))
        Revised (int32(1))
        New (int32(2))
    end

end %class

