classdef SearchRequest < macrobond.JSONMapper
% SearchRequest Information about a search request
% 
% SearchRequest Properties:
%   includeDiscontinued - If True, discontinued entities will be included in the search - type: logical
%   filters - One or more filters that specifies what to search for - type: array of SearchFilter
%   suggestFilters - If set to true, include suggestions of filters in the search result. - type: logical
%   noMetadata - If set to true, no metadata but only the name of the entities will be returned. - type: logical
%   allowLongResult - If set to true, allow for longer search results. noMetaData must be set to true. limit must be 0 or omitted. - type: logical
%   limit - Limit the number of results, must be a value between 1 and 10 000. Default is 500. - type: int32

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 3.0.0


    % Class properties
    properties
        % includeDiscontinued - If True, discontinued entities will be included in the search - type: logical
        includeDiscontinued logical { macrobond.JSONMapper.fieldName(includeDiscontinued,"includeDiscontinued")}
        % filters - One or more filters that specifies what to search for - type: array of SearchFilter
        filters macrobond.models.SearchFilter { macrobond.JSONMapper.fieldName(filters,"filters"), macrobond.JSONMapper.JSONArray}
        % suggestFilters - If set to true, include suggestions of filters in the search result. - type: logical
        suggestFilters logical { macrobond.JSONMapper.fieldName(suggestFilters,"suggestFilters")}
        % noMetadata - If set to true, no metadata but only the name of the entities will be returned. - type: logical
        noMetadata logical { macrobond.JSONMapper.fieldName(noMetadata,"noMetadata")}
        % allowLongResult - If set to true, allow for longer search results. noMetaData must be set to true. limit must be 0 or omitted. - type: logical
        allowLongResult logical { macrobond.JSONMapper.fieldName(allowLongResult,"allowLongResult")}
        % limit - Limit the number of results, must be a value between 1 and 10 000. Default is 500. - type: int32
        limit int32 { macrobond.JSONMapper.fieldName(limit,"limit")}
    end

    % Class methods
    methods
        % Constructor
        function obj = SearchRequest(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { macrobond.JSONMapper.ConstructorArgument } = []
                inputs.?macrobond.models.SearchRequest
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

